# 备选方案：使用不同的部署策略
- name: Deploy
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "github-actions@users.noreply.github.com"
    git checkout --orphan gh-pages
    git reset --hard
    cp -r public/* .
    git add .
    git commit -m "Deploy to GitHub Pages"
    git push origin gh-pages --force