name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 修改 Hugo 构建命令，确保生成 public 目录
      - name: Build with Hugo
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}"
          echo "Hugo build completed"
          if [ -d "public" ]; then
            echo "Public directory exists:"
            ls -la public/
          else
            echo "Error: public directory not found!"
            exit 1
          fi

      # 配置工件名称
      - name: Fix permissions
        run: |
          chmod -R a+r public
          find public -type d -exec chmod a+x {} \;

      - name: Upload Pages artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: "public/"
          retention-days: 1

      # 添加一个检查步骤
      - name: Check artifact status
        run: |
          echo "Upload status: ${{ steps.upload.outcome }}"
          echo "Upload result: ${{ steps.upload.outputs.artifact_id }}"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          artifact_name: "github-pages"  # 确保和上传时使用相同的名称